### ISSUE TITLE
import style from sld

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#103]
i've been thinking about vice versa use cases that transform SLD/geoexplorer into qgis style.

- a typical use case is highlighted [here](https://geoforum.nl/t/stijlbestand-pdok-bodemkaart-gezocht/3565), user wanting to import a style from an exiting wms and use it locally to style a vector dataset (wfs response)
- import a project into qgis from arcmap

**Comment by jodygarnett** [comment]
Note this needs to be implemented first in the command line library.
