### ISSUE TITLE
Geocat failed to install on QGIS 3.10.3 standalone install

### ISSUE THREAD

**Issue by gitDimg** [GeoCat/qgis-bridge-plugin#105]
Hi!

I just simply cant install GeocatBridge on QGIS 3.10.3(ltr). Also tried the OSGeo4W with same results.
Works on QGIS 3.12.0. 

Tried a couple of times, also wiped profile.

---------------------
ModuleNotFoundError: No module named 'lxml.etree' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\__init__.py", line 11, in classFactory
    from .plugin import GeocatBridge
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\plugin.py", line 13, in 
    from .ui.bridgedialog import BridgeDialog
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\ui\bridgedialog.py", line 8, in 
    from .publishwidget import PublishWidget
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\ui\publishwidget.py", line 48, in 
    from geocatbridge.publish.geonetwork import GeonetworkServer
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\geonetwork.py", line 9, in 
    import lxml.etree as ET
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml.etree'

------------
Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.3-A Coruña A Coruña, 0e1f846438 

Python sökväg:
C:\Users\KlanteVolante\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\karika
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/KlanteVolante/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\KlanteVolante\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\geocatbridge\libs
C:\Users\KlanteVolante\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\geocatbridge\libs\bridgestyle
-------------

**Comment by pvgenuchten** [comment]
Hi @GitDimg, seems in some installations of QGIS the lxml library is not pre-installed. 
Try installing it manually from https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml

**Comment by volaya** [comment]
Hi, 

Looks like your QGIS 3.10 installation lacks the required lxml library, while your 3.12 one has it. The Bridge plugin assumes it is installed. Not sure if that might be a packaging error in 3.10

You can maybe install it manually in the python used by your QGIS 3.10 installation. Here you have instructions for installing additional python libraries in QGIs, with a particular example of the lxml library

https://www.lutraconsulting.co.uk/blog/2016/03/02/installing-third-party-python-modules-in-qgis-windows/

**Comment by gitDimg** [comment]
OK, thank you for inputs. I'm also thinking about maybe there is a packaging error in 3.10. 
Its the third version of QGIS-OSGeo4W-3.10.3 out in just a week. In the first version the setup failed completly. 
I guess I have to wait and see. 
Also thinking of open a case on QGIS for missing lxml library.

As I see it for me its not an alternative to manually install lxml because I've have to roll this out to a couple of computers.

Thank you for your support!

**Comment by gitDimg** [comment]
Reported my issue to https://github.com/qgis/QGIS/issues/34838, and got this answer:
python3-lxml is no actual dependency of QGIS and was not included in the ltr packages. Added to qgis-ltr-full in osgeo4w.

So, the way to get GeoCatBridge working is to install lxml as proposed earlier if using the standalone QGIS 3.10.3 ltr.
