### ISSUE TITLE
Plugin causes crash on Ubuntu 19.10 when adding table with no geometry from Postgis 

### ISSUE THREAD

**Issue by rjhale1971** [GeoCat/qgis-bridge-plugin#106]
QGIS on Ubuntu 19.10 Revision 409bcf8eaa

Here is how (so far) I've replicated this crash. 

1. Add Geocat Plugin 
2. Make sure it's activated. 
3. Connect to PostgreSQL/PostGIS 
4. Add a table with no geometry 
5. QGIS Crashes with **QGIS died on signal 11Aborted (core dumped)**

At first I thought this was a problem with Ubuntu on 19.10 - reported here: https://github.com/qgis/QGIS/issues/34851 but it couldn't be replicated. I built a new profile and started adding plugins until something crashed. 

I created a new plugin with only the bridge plugin and was able to replicate the crash. I've had this happen with PostgreSQL/PostGIS  11/2.5 and 12/3

**Comment by alhabshi3k** [comment]
Similar case with me. I consider it a Serious Side-Effect!

I am using GeoCatBridge ver. 4.0.2 with QGIS 3.12 on Windows 10 (64-bit). 

The steps to reproduce the error:
1.  After installing GeoCatBridge ver 4.0.2 on a New QGIS clean profile and being Activated, everything looks Ok. 
2. When drag-n-drop a CSV file, SQLite table or Geopackage table **_with geometry_** from QGIS Browser panel to the Layer Panel, QGIS hang then crash. 

The QGIS crash reports the following:

> Stack Trace
> 
> QBitArray::QBitArray :
> QgsAction::name qgsaction.h:124
> QgsRuleBasedRenderer::convertFromRenderer qgsrulebasedrenderer.cpp:1304
> meth_QgsRuleBasedRenderer_convertFromRenderer sip_corepart0.cpp:119295
> PyMethodDef_RawFastCallKeywords :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyMethodDef_RawFastCallKeywords :
> PyEval_EvalFrameDefault :
> PyFunction_FastCallDict :
> PyMethodDef_RawFastCallDict :
> PyObject_Call :
> PyInit_QtCore :
> PyInit_QtCore :
> PyInit_QtCore :
> PyInit_QtCore :
> PyInit_QtCore :
> QMetaObject::activate :
> QgisInterface::currentLayerChanged moc_qgisinterface.cpp:717
> QMetaObject::activate :
> QgisApp::activeLayerChanged moc_qgisapp.cpp:2691
> QgisApp::onActiveLayerChanged qgisapp.cpp:676
> QgisApp::handleDropUriList qgisapp.cpp:1994
> ::operator() qgisapp.cpp:1878
> QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:422
> QMetaObject::activate :
> QTimer::timerEvent :
> QObject::event :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify qgsapplication.cpp:418
> QCoreApplication::notifyInternal2 :
> QEventDispatcherWin32Private::sendTimerEvent :
> QEventDispatcherWin32::processEvents :
> UserCallWinProcCheckWow :
> DispatchMessageWorker :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main main.cpp:1609
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> 
> QGIS Info
> QGIS Version: 3.12.0-Bucure?ti
> QGIS code revision: cd141490ec
> Compiled against Qt: 5.11.2
> Running against Qt: 5.11.2
> Compiled against GDAL: 3.0.4
> Running against GDAL: 3.0.4
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.18363
>

**Comment by volaya** [comment]
This should fix it:

https://github.com/GeoCat/qgis-bridge-plugin/commit/96e396077481e5076340a9da90d9c67e4548cbeb

**Comment by mradamcox** [comment]
This may solve the issue, but it looks like there hasn't been a new release of GeoCatBridge since Feb of this year. Any plans for an update? Just encountered this issue getting crashes whenever I try to load a CSV without geometry.

**Comment by gubuntu** [comment]
Yes this is also the case on Mac with QGIS 3.14 and 3.10, loading a non-spatial table from any source via any driver crashed QGIS. Problem goes away when GeoCatBridge is disabled.
