### ISSUE TITLE
Upgrade plugin from 4.0 to 4.0.2 is not possible

### ISSUE THREAD

**Issue by cvanlith** [GeoCat/qgis-bridge-plugin#107]
QGIS fails to upgrade the GeoCatBridge plugin from 4.0 to 4.0.2 is the workspace field has been filled in 4.0.
Loading the settings will crash the plugin.
After removing the Bridge settings from the QGIS ini file, all works well again.

**Comment by volaya** [comment]
Hi. Thanks for the report. This was a known bug, but there is a fix already added to the current master code. Now if there are servers defined from a previous version (with a different set of configuration parameters, which was the issue in this case), no error is raised. The servers will not be recovered, and an empty set of them will appear in the Bridge dialog, making it necessary to add servers again,

**Comment by jodygarnett** [comment]
@volaya will you close this bug when a version is released? Or can we close this now :)

**Comment by volaya** [comment]
I guess it can be closed already
