### ISSUE TITLE
mapfile name should be {project}.map and/or have own folder

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#11]
You probably have to create a number of files per publish action, so would be better to create a folder for each published map.

I noticed the name of the generated mapfile is mapfile.map, this could work if each publish has its own folder. Alternative is to use {project}.map as filename

When storing locally, the 'publish map data' status is false, however the data and map files were created successfully in that folder, shouldn't the 'publish map data' status be true?

![image](https://user-images.githubusercontent.com/299829/65996503-d10d1180-e497-11e9-9096-1c4824155c84.png)

**Comment by volaya** [comment]
The mapfile has now the name of the project (or "mymap" if the project is not saved)

The "OFF" value was due to a bug. Fixed already

**Comment by pvgenuchten** [comment]
@volaya i actually think we should refactor so each mapfile has its own folder, for example we include a {layer}.map for each layer, but if multiple mapfiles include a layer with the same name these files would be overwritten, i would suggest a file structure like

- {project/workspace}
  - maps
    - {project}.map 
    - n * {layer}.map 
    - n * {layer}_symbols.map
  - data
    - n * {layer}.shp/gpkg/tiff
  - templates
    - n * {layer}.ttl
