### ISSUE TITLE
Support for CSW servers

### ISSUE THREAD

**Issue by Samweli** [GeoCat/qgis-bridge-plugin#115]
Hi,

While looking around at the plugin code I found a line here https://github.com/GeoCat/qgis-bridge-plugin/blob/95f967fb61bc15ead1180c9580b8d805690076f4/geocatbridge/ui/serverconnectionswidget.py#L382
which comments out an option for dealing with metadata from and to CSW servers, do you have a plan on supporting this? I think it would be nice if the plugin could also support CSW metadata catalogs.

Thanks

**Comment by pvgenuchten** [comment]
Hi @Samweli, do you have any specific product in mind you would like to see supported, mind that the product needs to have 'CSW transaction' support (being able to publish records via CSW. Bridge already supports the geonetwork catalogue, via its vendor-api.

**Comment by Samweli** [comment]
Hi @pvgenuchten, 

> do you have any specific product in mind you would like to see supported

I'm looking at using the plugin with a pycsw catalogue. Is this currently possible? If not, are there any plans for supporting the pycsw based servers?

**Comment by GeoSander** [comment]
Closing old tickets.

Note on this one: Bridge could (in theory) support any service that offers an API to *publish* data to it. To my knowledge, PyCSW (and also pygeoapi) do not offer this possibility (yet).
