### ISSUE TITLE
GeoCat Bridge Error when loading a project in QGIS

### ISSUE THREAD

**Issue by sindile** [GeoCat/qgis-bridge-plugin#120]
Hello,
I get the following error when loading aproject in QGIS

ValueError: not enough values to unpack (expected 4, got 3) 
Traceback (most recent call last):
  File "/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 62, in updateForCurrentLayer
    geostyler, _, _, geostylerWarnings = convert(layer)
ValueError: not enough values to unpack (expected 4, got 3)

Python version: 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0] 
QGIS version: 3.14.16-Pi Pi, a235a149f0 

Python Path:
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LAStools
/usr/share/qgis/python
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/sindile/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/sindile/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle
/home/sindile/Documents/bayersnaude/data

**Comment by sindile** [comment]
I am using the master version of GeoCat Bridge.

**Comment by pvgenuchten** [comment]
Hi  @sindile thanx for reporting, can you add a project file and some data to reproduce the issue

**Comment by sindile** [comment]
Hi @pvgenuchten 
[testdata.zip](https://github.com/GeoCat/qgis-bridge-plugin/files/5335117/testdata.zip)

**Comment by GeoSander** [comment]
This issue should no longer occur in the [latest Bridge 4.1](https://plugins.qgis.org/plugins/geocatbridge/version/4.1.3/) release.
Closing this now.

Sander
