### ISSUE TITLE
QGIS crashes when opening large tables

### ISSUE THREAD

**Issue by malenalibman** [GeoCat/qgis-bridge-plugin#126]
I'm on ubuntu 20.04 (plama kde), QGIS 3.16.3-Hannover. I'm having problems with some csv tables, when I import it through the data source manager QGIS closes, no error report, nothing. I tried importing the table to postgresql and geopackage, but when I want to add it to the canvas, again QGIS closes no warning.

The issue only stopped when I removed qgis-bridge-plugin, I wasn't able to find an error log to find what was the problem.

This is the csv file for reference: https://servicios.transporte.gob.ar/gobierno_abierto/descargar.php?t=mcancelaciones&d=mlinea

**Comment by GeoSander** [comment]
Thank you for reporting this issue and attaching some test data, @malenalibman. We will have a look at your CSV file to see if we can reproduce this.
