### ISSUE TITLE
QGIS crash when opening PostGIS table without geometry

### ISSUE THREAD

**Issue by rmarzocchi84** [GeoCat/qgis-bridge-plugin#127]
I encountered the same issue in QGIS 3.10.14 and 3.16. It seem related to geocatbridge plugin. 

https://github.com/qgis/QGIS/issues/41252

Yo can try with a simple postgresql table but I have the same issu on different DB, schema and table (always table without geometry):
```
CREATE TABLE schemaname.pontiviadottisottopassi_tipo_tracciato (
    id character varying NOT NULL,
    descrizione varchar,
    CONSTRAINT pontiviadottisottopassi_tipo_tracciato_pkey PRIMARY KEY (id)
);

INSERT INTO schemaname.pontiviadottisottopassi_tipo_tracciato VALUES ('1', 'Rettilineo' );
INSERT INTO schemaname.pontiviadottisottopassi_tipo_tracciato VALUES ('2', 'In curva' ); 
```

**Comment by rmarzocchi84** [comment]
sorry it is similar to this https://github.com/GeoCat/qgis-bridge-plugin/issues/126 I hobe my example can be useful, but obviously I can do more test

**Comment by GeoSander** [comment]
Who needs geometry, right? ;)
Thank you for reporting! Because it's a duplicate, I will close this issue now, if you don't mind.

**Comment by rmarzocchi84** [comment]
> Who needs geometry, right? ;)

my postgresql table is only attribute table (without geometry). I used to create a value relation in QGIS

**Comment by GeoSander** [comment]
I was just kidding :)
_Especially_ non-spatial tables should not throw errors in Bridge!
