### ISSUE TITLE
源代码放在qgis插件下无法运行，提示缺少bridgestyle文件

### ISSUE THREAD

**Issue by funny12138** [GeoCat/qgis-bridge-plugin#128]
Translation: The source code cannot be run under the qgis plug-in, and it prompts that the bridgestyle file is missing

**Comment by GeoSander** [comment]
When you're running Bridge from source code (please checkout tags only, as the current HEAD is unstable), you'd have to do ```git clone``` with the ```--recursive``` option as described in the [ReadMe](https://github.com/GeoCat/qgis-bridge-plugin#readme) file.

**Comment by funny12138** [comment]
thanks GeoSander, i have fixed it
