### ISSUE TITLE
TypeError on label definition

### ISSUE THREAD

**Issue by jusabatier** [GeoCat/qgis-bridge-plugin#132]
I'm trying to define a simple label which is an aggragate of two fields, and when validate the style, I get an error from GeoCat Bridge plugin : 

> TypeError: cannot serialize None (type NoneType) 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1052, in _escape_attrib
>     if "&" in text:
> TypeError: argument of type 'NoneType' is not iterable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 49, in updateLayer
>     self.updateForCurrentLayer()
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 59, in updateForCurrentLayer
>     sld, _, sldWarnings = layerStyleAsSld(layer)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 18, in layerStyleAsSld
>     sldString, sldWarnings = sld.fromgeostyler.convert(geostyler)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/sld/fromgeostyler.py", line 72, in convert
>     sldstring = ElementTree.tostring(root, encoding='utf8', method='xml').decode()
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1109, in tostring
>     ElementTree(element).write(stream, encoding,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 748, in write
>     serialize(write, self._root, qnames, namespaces,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 913, in _serialize_xml
>     _serialize_xml(write, e, qnames, None,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 913, in _serialize_xml
>     _serialize_xml(write, e, qnames, None,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 913, in _serialize_xml
>     _serialize_xml(write, e, qnames, None,
>   [Previous line repeated 4 more times]
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 906, in _serialize_xml
>     v = _escape_attrib(v)
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1075, in _escape_attrib
>     _raise_serialization_error(text)
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1029, in _raise_serialization_error
>     raise TypeError(
> TypeError: cannot serialize None (type NoneType)
> 
> 
> Version de Python : 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0] 
> Version de QGIS : 3.16.9-Hannover Hannover, 9f8d2f7942 
> 
> Chemin Python :
> /usr/share/qgis/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python39.zip
> /usr/lib/python3.9
> /usr/lib/python3.9/lib-dynload
> /home/jusabatier/.local/lib/python3.9/site-packages
> /usr/local/lib/python3.9/dist-packages
> /usr/lib/python3/dist-packages
> /usr/lib/python3.9/dist-packages
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/forms
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle

**Comment by GeoSander** [comment]
Hi @jusabatier, 

You might want to give the [latest Bridge 4.1](https://plugins.qgis.org/plugins/geocatbridge/version/4.1.3/) release a try. It could well be that this issue has been solved. Please let me know if it did, so I can close this issue.

Sander

**Comment by jusabatier** [comment]
Hi,

I tried to upgrade the extension to the latest version, but now it bug during the startup of QGIS : 

> Impossible de charger l'extension 'geocatbridge' provoque une erreur lors de l'appel à sa méthode classFactory() 
> 
> AttributeError: 'PosixPath' object has no attribute 'startswith' 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/pkgutil.py", line 416, in get_importer
>     importer = sys.path_importer_cache[path_item]
> KeyError: PosixPath('/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/servers/models')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/__init__.py", line 18, in classFactory
>     return GeocatBridge(iface)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/plugin.py", line 36, in __init__
>     manager.loadConfiguredServers()
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/servers/manager.py", line 167, in loadConfiguredServers
>     return deserializeServers(server_config)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/servers/manager.py", line 134, in deserializeServers
>     s = _initServer(server_type, **properties)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/servers/manager.py", line 35, in _initServer
>     cls = getModelLookup().get(type_name)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/servers/__init__.py", line 31, in getModelLookup
>     for (_, module_name, _) in iter_modules([package_dir]):
>   File "/usr/lib/python3.9/pkgutil.py", line 130, in iter_modules
>     for i in importers:
>   File "/usr/lib/python3.9/pkgutil.py", line 420, in get_importer
>     importer = path_hook(path_item)
>   File "", line 1601, in path_hook_for_FileFinder
>   File "", line 1476, in __init__
>   File "", line 177, in _path_isabs
> AttributeError: 'PosixPath' object has no attribute 'startswith'
> 
> 
> Version de Python : 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0] 
> Version de QGIS : 3.16.9-Hannover Hannover, 9f8d2f7942 
> 
> Chemin Python :
> /usr/share/qgis/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python39.zip
> /usr/lib/python3.9
> /usr/lib/python3.9/lib-dynload
> /home/jusabatier/.local/lib/python3.9/site-packages
> /usr/local/lib/python3.9/dist-packages
> /usr/lib/python3/dist-packages
> /usr/lib/python3.9/dist-packages
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/forms
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle

**Comment by GeoSander** [comment]
Yes, Bridge uses the Python built-in library ``pkgutil``, but unfortunately, there is a known bug in the Python 3.9 release for that library: https://bugs.python.org/issue44061

Please downgrade your Python version to 3.8 and Bridge should work fine.

**Comment by jusabatier** [comment]
The problem is that Python 3.9.5 is actually the built-in QGis version, and I don't know if it's possible to change it simply...

I think I will wait next QGis upgrade.

**Comment by GeoSander** [comment]
Alternatively, you can hack the Bridge code yourself and change [line 31](https://github.com/GeoCat/qgis-bridge-plugin/blob/master/geocatbridge/servers/__init__.py#L31) in `geocatbridge/servers/__init__.py` to:

```for (_, module_name, _) in iter_modules([str(package_dir)]):```

That should at least get rid of the `pkgutil` error.

**Comment by jusabatier** [comment]
Ok, your tip fix the loading error for the plugin, but I still get the same error when defining a style with composed label : 

> TypeError: cannot serialize None (type NoneType) 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1052, in _escape_attrib
>     if "&" in text:
> TypeError: argument of type 'NoneType' is not iterable
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/styleviewerwidget.py", line 48, in updateLayer
>     self.updateForCurrentLayer()
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/styleviewerwidget.py", line 58, in updateForCurrentLayer
>     sld, _, sld_warnings = layerStyleAsSld(layer)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 15, in layerStyleAsSld
>     sldString, sldWarnings = sld.fromgeostyler.convert(geostyler)
>   File "/home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/sld/fromgeostyler.py", line 72, in convert
>     sldstring = ElementTree.tostring(root, encoding="utf8", method="xml").decode()
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1109, in tostring
>     ElementTree(element).write(stream, encoding,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 748, in write
>     serialize(write, self._root, qnames, namespaces,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 913, in _serialize_xml
>     _serialize_xml(write, e, qnames, None,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 913, in _serialize_xml
>     _serialize_xml(write, e, qnames, None,
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 913, in _serialize_xml
>     _serialize_xml(write, e, qnames, None,
>   [Previous line repeated 4 more times]
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 906, in _serialize_xml
>     v = _escape_attrib(v)
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1075, in _escape_attrib
>     _raise_serialization_error(text)
>   File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1029, in _raise_serialization_error
>     raise TypeError(
> TypeError: cannot serialize None (type NoneType) 
> Version de Python : 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
> Version de QGIS : 3.20.1-Odense (Odense 2755615b9f) 
> Python path: 
> /usr/share/qgis/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/bin/python3.10
> /usr/lib/python39.zip
> /usr/lib/python3.9
> /usr/lib/python3.9/lib-dynload
> /home/jusabatier/.local/lib/python3.9/site-packages
> /usr/local/lib/python3.9/dist-packages
> /usr/lib/python3/dist-packages
> /usr/lib/python3.9/dist-packages
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/cadastre/forms
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
> /home/jusabatier/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle

**Comment by GeoSander** [comment]
That's unfortunate. This error occurs in Python's built-in ElementTree library, which in turn is used by the Bridgestyle library (included in Bridge), so the bug should actually be reported [here](https://github.com/GeoCat/bridge-style/issues).

I'm no styling expert actually, but did you also see this? https://geocat.github.io/qgis-bridge-plugin/v4.1/supported_symbology.html
Did you use some kind of (unsupported) expression in the label by any chance?

Nevertheless, we might have to do some sanitization or `None` test before parsing the XML as a string...

**Comment by jusabatier** [comment]
> I'm no styling expert, but did you also see this? https://geocat.github.io/qgis-bridge-plugin/v4.1/supported_symbology.html
> Did you use some kind of (unsupported) expression in the label by any chance?

I take a look to this documentation and it says that simple labelling and label's background are both supported.

> Nevertheless, we might have to do some sanitization or None test before parsing the XML as a string...

I agree if it allow at least to not have an error message from the plugin each time user define an unsupported style.

**Comment by GeoSander** [comment]
Thanks for creating the issue in the Bridgestyle repo. I'll close this issue now, if that's OK.
