### ISSUE TITLE
GeoCatBridge not able to publish layer group into geoserver from QGIS

### ISSUE THREAD

**Issue by asifgis** [GeoCat/qgis-bridge-plugin#135]
I am using the latest version of GeoCatBridge plugin 4.1.3 with QGIS. The issue i am facing not be able to publish the layers group. I want to put all my layers in qgis under one group and want those layer into geoserver under the same group. The layers are published successfully but there is no group available into geserver for reference i am also attaching the image. I previously published the layers group successfully with the older version . Is that the issue with this new version or there is something else?
![issue_publishing_layers_group](https://user-images.githubusercontent.com/12974459/138291062-e63fdfc9-48f9-4ee0-a047-a77861a960af.PNG)
.

**Comment by asifgis** [comment]
Ok thanks for Updating

**Comment by GeoSander** [comment]
FYI, we have just released Bridge 4.2 (available on the QGIS plugin repository), which should be able to properly publish layer groups.
