### ISSUE TITLE
qt dependency missing on fedora

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#140]
some pyqt dependency is missing in fedora 34, it may be a more generic qgis error

![image](https://user-images.githubusercontent.com/299829/139824318-a842adff-c343-449a-bd53-f45ad631d4ce.png)

fedora 34
qgis 2.20

**Comment by pvgenuchten** [comment]
Issue is resolved by installing manually plugin: python3-qt5-webkit.x86_64

**Comment by GeoSander** [comment]
Note that this technically isn't a Bridge dependency, since PyQt5 should ship with QGIS. So if anything, this is a QGIS issue.
