### ISSUE TITLE
Cannot add server on macOS

### ISSUE THREAD

**Issue by alwaysdaylast** [GeoCat/qgis-bridge-plugin#146]
Env：

QGIS version | 3.22.3-Białowieża | QGIS code revision | 1628765ec7
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.2
  |   |   |  
Active Python plugins
geocatbridge | 4.2.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

When i new a connection in the Bridge pulgin, it does not respond at all
Step1:
![image](https://user-images.githubusercontent.com/87117565/155481402-16bd6074-5f32-4113-ae9c-92cd626d218c.png)

Step2:
![image](https://user-images.githubusercontent.com/87117565/155481766-2397f6f3-b2fe-472f-8eff-77bc2e38eb9f.png)

i can not click any these server types at all at step 2

I also made a screen recording for this

https://user-images.githubusercontent.com/87117565/155484541-a0446669-7c7f-41d1-b3b8-f8d698402658.mov

**Comment by GeoSander** [comment]
Hi @alwaysdaylast,

Thanks for reporting this issue. We have observed this bug with several other macOS users too, but not consistently. So it seems to occur with specific macOS versions and/or QGIS and/or Qt versions. 
The trick is to find out in which situation it happens. Only then can we find out *why* it happens and develop a workaround...

Looking at the video, the user interface seems to deadlock, so my first guess is that this is a Qt-on-macOS related problem (there are plenty of Qt-issues on Mac...).

Sander

**Comment by GeoSander** [comment]
Update: it may be related to [this SO issue](https://stackoverflow.com/questions/67458656/why-does-pyqt-menu-get-frozen-on-macos).
So perhaps the workaround that is suggested (disabling the macOS native menu) might do the trick:

`menu.setNativeMenuBar(False)`

Are you able and willing to edit the Python code yourself @alwaysdaylast, so you can try if it works?
I can point you at the exact location.

**Comment by GeoSander** [comment]
Hi @alwaysdaylast,

I think I have found (and fixed) the issue.
If you would like to edit the code yourself (the next official release will take some more weeks), you can see what I did in the commit: https://github.com/GeoCat/qgis-bridge-plugin/commit/aa8e0efec09828b66bcb26a8ee08acadcf806be6

Sander

**Comment by alwaysdaylast** [comment]
For now, I have gone back to qgis version 3.16 and reinstall the the plugin, it works fine

**Comment by madlenkk** [comment]
Hi, 
I would like to report exactly the same problem on Windows 10. 
I am not able to add any new server (nor via import from json) in GeoCat Bridge version 4.2.1.

I went back to v4.1.3, but I am really looking forward to use the new version already, because it seems there is an important fix that I greatly appreciate (label level Z=0 was removed from SLD).

Thanks for your work,
Magdalena

**Comment by GeoSander** [comment]
@alwaysdaylast I have verified this fix with someone on macOS 12.2.1 and QGIS 3.24 and it also seemed to work. In case you wish to upgrade to 3.22+.

Anyway, good to hear that it worked out for you. Closing this ticket.

@madlenkk The problem you are having seems to be a different one, as the problem above does not affect Windows nor the "Import from JSON" functionality. Could you please [create another issue](https://github.com/GeoCat/qgis-bridge-plugin/issues/new/choose) that describes what happens? Do you see errors in the "Log Messages" window (GeoCat Bridge tab) of QGIS? Which errors do you get when you (a) press the 'New Server' button and (b) selected a JSON file for import?

**Comment by GeoSander** [comment]
FYI @alwaysdaylast: There is a new version on the QGIS plugin repo (4.2.2) that contains the fix, so you can update using the QGIS Plugin Manager (it's a good idea to restart QGIS after the update).

@madlenkk: I was actually waiting for an issue report from you, so I could include the fix in the new release, but I haven't heard back. Are you still willing to share something in a new issue?

**Comment by madlenkk** [comment]
@GeoSander Finally I´ve solved the problem by installing Python 3.10 on Windows and now everything works well.
Thanks!
