### ISSUE TITLE
environment : qgis3.22-python3.9 

### ISSUE THREAD

**Issue by gengyanlei** [GeoCat/qgis-bridge-plugin#150]
installed error: import lxml.etree as ET error.
only in qgis3.16 is successful.

**Comment by GeoSander** [comment]
Hi @gengyanlei,

Thanks for your patience...
Did you install QGIS using the standalone installer or the OSGeo4W installer? Or are you not on Windows?
Either way, the `lxml` library used to be included in 3.16, but that may no longer be the case for 3.22. If you use the OSGeo4W installer, you can choose the advanced install options and make sure that the `lxml` library is checked/installed.
For standalone QGIS installations, you'll have to manually install `lxml` from PyPI using `pip`, for example. But the exact workflow depends on your OS.

Sander

**Comment by GeoSander** [comment]
### Update:

The latest [Bridge release 4.3](https://plugins.qgis.org/plugins/geocatbridge/version/4.3/) from yesterday (currently still awaiting approval from the QGIS plugin repo) will no longer raise an exception if `lxml` is missing. Instead, it will warn the user that this dependency is required and needs to be installed if you wish to publish metadata records with Bridge.

**Users who only use Bridge to publish layers to GeoServer/MapServer do not need to install `lxml`.**

Unfortunately, the XSLT transform that this library provides _really_ is required for metadata transformations (e.g. from QMD to ISO19139). Shipping Bridge _with_ the `lxml` lib included really is a last resort, which we do not wish to do at this point. As mentioned in my post above, users who need to work with metadata can install the library using `pip` or the `OSGeo4W` setup (= recommended approach).
