### ISSUE TITLE
Bridge unregisters Geopackages previously uploaded to Geoserver

### ISSUE THREAD

**Issue by Ortimis** [GeoCat/qgis-bridge-plugin#153]
**Describe the bug**
When uploading a layer in a geopackage to a Geoserver instance, all the other geopackages previously uploaded from the same QGIS project are unregistered as a data source.

**To Reproduce**
1. Set up a Geoserver and a QGIS, install the Geocat bridge plugin
2. Upload and publish some geopackage
3. Upload a second and differently named geopackage from the same QGIS project
4. The previous geopackage has been unregistered as a data source

**Expected behavior**
Previous geopackages should stay as a data source, no matter how they were uploaded

**Environment info (please complete the following information):**
 - OS: Windows
 - QGIS version: 3.28.0 Firenze
 - Bridge version: 4.3.1
 - Python version: 3.10.8

Thanks to the whole team for an extremely helpful plugin!

**Comment by GeoSander** [comment]
Hi @Ortimis,

Thanks for reporting this issue.

So to be clear: this is not a bug, but it is exactly how Bridge behaves in the _current_ version.
When you publish _anything_ to the same GeoServer workspace as before, it clears everything within that workspace (so also the datastores). 

We realize that a lot of QGIS users seemingly do not want this (although we never get a lot of community feedback to be honest), so we are working on Bridge version 5 now, which will have the ability to publish stuff to an existing workspace without removing anything (amongst other things).

For now, if you wish to preserve the GeoPackage, the only option would be to save your QGIS Project under another name and publish to another workspace...

Sander
