### ISSUE TITLE
Cannot accept credentials for GeoServer

### ISSUE THREAD

**Issue by JMG30** [GeoCat/qgis-bridge-plugin#154]
In Servers tab I'm trying to add a GeoServer, but I cannot accept username and password, that I entered. In dropdown combobox I cannot select another method (?) and it shows "No Authentication" all the time. Checking and unchecking checkboxes doesn't help either.

![obraz](https://user-images.githubusercontent.com/44444960/208302577-e921fde2-dd67-4a87-8b72-c7dc9dd8e3e3.png)

**Environment info:**
 - OS: Windows 10
 - QGIS version: 3.22.13 LTR Białowieża
 - Bridge version: 4.3.1
 - Python version: 3.9.5

**Comment by JMG30** [comment]
Sorry, my bad - it's all clear. I just never used authentication in QGIS and it was new to me. I'll have to read more careful next time.

**Comment by GeoSander** [comment]
Hi @JMG30, good that you resolved the issue and thanks for reporting back! 👍
Just out of curiosity: how did you get that `Enter Credentials` popup dialog to show up?

**Comment by JMG30** [comment]
Recently I reinstalled Windows, installed QGIS, then I just installed and wanted to use your plugin (for the first time in my life) and that's all.

Some time later I tried to add WMS and saw there is the same option, so I understood that the popup dialog is basically not related to your plugin.

BTW great plugin 👍

**Comment by GeoSander** [comment]
Ah right, gotcha. I was confused how you got that dialog - but now it makes sense.

Glad to hear that you like it!
