### ISSUE TITLE
GeoCat Bridge not recognizing layers and not publishing

### ISSUE THREAD

**Issue by stepsbystep** [GeoCat/qgis-bridge-plugin#159]
I installed GeoCat Bridge to move layers to PostGis on a Ubuntu server. Easy install. But I can't publish. I encountered two types of problems.

With some QGIS layers from world.qgz all the layers are identified but the data server does not show up on the "data server" dropdown. The Postgres server is set up in the Servers panel and the test connection works. 

With some of my layers, some coming from [this](https://data.cityofchicago.org/Facilities-Geographic-Boundaries/Boundaries-Community-Areas-current-/cauq-8yn6#Export) site, I get the message that no supported layers are found. I was surprised. I checked the repo code and found the function that determines if a layer is supported, isSupportedLayer in layers.py, and this test for support:

```
 layer.isValid() and layer.isSpatial() and layer.crs().isValid() and not layer.isTemporary() and \
        layer.type() in (QgsMapLayer.VectorLayer, QgsMapLayer.RasterLayer) and layer.dataProvider().name() != "wms"

```
I ran this test on some of my layers in the Python console and they test out as supported. 

I am running QGIS 3.28.4 on a Windows 10 machine. Also, I'm using GeoCat Bridge 4.3.2 and Python 3.9.

**Comment by GeoSander** [comment]
Hi @stepsbystep,

Perhaps this is unclear and needs to be documented better, but to Bridge, PostGIS is not a "data server". PostGIS connections are intended to be used by a datastore when publishing to GeoServer with direct access. 
So this works as designed.

If you wish to export data to PostGIS only, we'd recommend another QGIS plugin like DB Manager or PostGIS Manager for example. These will probably offer more powerful support for databases anyway. 

Sander

**Comment by stepsbystep** [comment]
Thank you Sander! I sort of suspected this might be the case at first, but it was unclear, so I thought I'd try. 

Thanks for the pointer to DB Manager. I should have figured that out. 

I'm sorry to have troubled you on a Friday afternoon. 

Barry

**Comment by GeoSander** [comment]
No problem, Barry. 
I'm hoping that DB Manager will be able to help you out! 

Sander
