### ISSUE TITLE
Couldn't load plugin on QGIS 3.16

### ISSUE THREAD

**Issue by geraldo** [GeoCat/qgis-bridge-plugin#160]
metadata.txt states that this plugin should work on QGIS 3.16, but actually it doesn't. On installing the plugin I get a an fatal error from included [bridge-style](https://github.com/GeoCat/bridge-style/) library:

![qgis316](https://github.com/GeoCat/qgis-bridge-plugin/assets/336371/d855f9be-73d1-4e3a-ba67-fa80167cc461)

Versión de Python: 3.6.9 (default, Dec  8 2021, 21:08:43) [GCC 8.4.0]
Versión de QGIS: 3.16.16-Hannover Hannover, f5778a89df 

PS: On QGIS 3.22 everything works fine.

**Comment by GeoSander** [comment]
Thanks for reporting @geraldo. Seems that the `BinaryOperator` that is used in `bridgestyle` is "too new" for 3.16. The operator stuff was added recently and I don't think that it was tested on 3.16 anymore...
