### ISSUE TITLE
Layers stored in /tmp/ are not listed as potential uploads

### ISSUE THREAD

**Issue by kannes** [GeoCat/qgis-bridge-plugin#163]
**Describe the bug**
The Publish tab does not show layers that are stored in `/tmp/` (a temporary location to QGIS)

**To Reproduce**
1. Be on Linux
2. Load a GPKG from /tmp/
3. Look at the "Publish" tab

**Screenshots**
![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/7661092/836a1b54-f6e6-4c09-8404-3cb942fe168a)

**Environment info (please complete the following information):**
 - OS: Manjaro, Linux
 - QGIS version: 3.34.3
 - Bridge version: 4.4
 - Python version: 3.11.6

**Additional context**
I noticed that "memory" layers are also not shown so maybe some logic is used to filter out "temporary" layers. The logic should rather filter out "memory" layers I guess as files in /tmp/ (or a similar temporary dir on Windows) should probably work fine.

**Comment by kannes** [comment]
Ah, related to https://github.com/GeoCat/qgis-bridge-plugin/issues/162 I guess

**Comment by GeoSander** [comment]
Hi @kannes, I have built in an extra check that looks if the layer URI is a path if `layer.isTemporary()` is true. So that should hopefully resolve this issue.
Should be released soon in [4.4.1](https://plugins.qgis.org/plugins/geocatbridge/version/4.4.1/) once it has been accepted.
