### ISSUE TITLE
HTTPError: 500 Server Error: for url

### ISSUE THREAD

**Issue by JPPereira93** [GeoCat/qgis-bridge-plugin#180]
Hello,

When using geocat bridge I'm getting  an error while publishing data:

![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/90710707/f139a5ef-6d2c-45a8-823d-668b156120d9)

And then, watching the log i get:

![image](https://github.com/GeoCat/qgis-bridge-plugin/assets/90710707/29c7208e-20fc-4ef2-8e48-791b415781a5)

This is a new geoserver installed on a fresh machine, with the older geoserver url i didn't get any problems.

There are some curiosities about this:

I already published some data, but then, when doing a following publish, with the same project and same characteristics I now get that error and no layers are published, despite the workspace being created.

**Environment info (please complete the following information):**
 - OS: [Windows]
 - QGIS version: 3.26.3 Buenos Aires
 - Bridge version: 4.4.1
 - Python version: 3.10.8

**Comment by GeoSander** [comment]
Hi @JPPereira93, are you able to access the GeoServer logs? If so, could you please see there if there's anything peculiar related to the 500? You may have to switch on REST debug logging in the GeoServer global settings (which is quite verbose, so switch it back off once you are done reproducing the error).

Seems that you are running an Azure instance, correct? There may be a disk write access problem perhaps.

**Comment by JPPereira93** [comment]
Hello @GeoSander !

It was indeed a disk write access problem, I gave read/write permissions in geoserver_data folder where the workspaces were being created and now it works fine!

**Comment by GeoSander** [comment]
Good to hear @JPPereira93 and thanks for the feedback.
Closing this issue now.
