### ISSUE TITLE
QTwebkit is deprecated and not available anymore

### ISSUE THREAD

**Issue by cmikovits** [GeoCat/qgis-bridge-plugin#185]
**Describe the bug**
With QT 5.6 qtwebkit was removed and this plugin does not work anymore:

https://wiki.qt.io/New_Features_in_Qt_5.6#Removed_Modules

**Comment by GeoSander** [comment]
Guess I should use `WebEngine` instead: https://doc.qt.io/qtforpython-6/overviews/qtwebenginewidgets-qtwebkitportingguide.html

**Comment by GeoSander** [comment]
This essentially has become a duplicate of #152, which has been re-opened now.
Any progress will be tracked there.

**Comment by GeoSander** [comment]
Fixed and released in [GeoCat Bridge 4.5.0](https://plugins.qgis.org/plugins/geocatbridge/version/4.5.0/).
