### ISSUE TITLE
Dock widget is not removed on unload()

### ISSUE THREAD

**Issue by geraldo** [GeoCat/qgis-bridge-plugin#187]
Following an issue with reloading bridge-style with Plugin Reloader the author of the plugin pointet out that the dock widget is not effectively removed from QGIS window and it keeps running. He describes the reason and also provides a fix for the unload() function described at https://github.com/borysiasty/plugin_reloader/issues/37#issuecomment-2332569458

**Comment by GeoSander** [comment]
Thanks for bringing this up @geraldo. Didn't know there were issues with the style viewer window and Plugin Reloader. Will fix!

**Comment by GeoSander** [comment]
Fixed and released in [GeoCat Bridge 4.5.0](https://plugins.qgis.org/plugins/geocatbridge/version/4.5.0/).
