### ISSUE TITLE
geosever test connection, server error

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#30]
When testing the connection from geoserver config screen, there is instant error:
![image](https://user-images.githubusercontent.com/299829/67371798-3aef7700-f57d-11e9-87de-64631aecf85c.png)

but when monitoring network traffic, no request has been fired to geoserver

geoserver 2.13

**Comment by volaya** [comment]
fixed here https://github.com/GeoCat/qgis-bridge-plugin/commit/2f1849a451453b5cfaa0c6fc59c546d51d8874a4
