### ISSUE TITLE
GeoCatBridge Plugin 4.0 Release Candidate

### ISSUE THREAD

**Issue by jodygarnett** [GeoCat/qgis-bridge-plugin#31]
The plugin has been submitted as an experimental plugin to the egis plugin repository.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/629681/67515562-e297a280-f66c-11e9-9f21-be47a0913bf3.png">

Testing:
- Scope: "Plugin to publish data and metadata to different catalogs." we could update this to indicate map server, geoserver and styling functionality also.
- Version 4.0.0-RC (or Version 4.0-RC as appropriate)
- issue tracker link is broken (points to https://github.com/geocat/qgis-geocatbridge-plugin/issues)
- code repository link is broken (points https://github.com/geocat/qgis-geocatbridge-plugin)
- tag repository

**Comment by jodygarnett** [comment]
For the "lxml library" is it worthwhile to package this as a separate QGIS plugin (as it would not change often)? Or is it not common for plugins to depend on other plugins ...

**Comment by jodygarnett** [comment]
Proposed:

> GeoCat Bridge offers a one-click publishing experience for QGIS Desktop. Create great looking maps and publish them to GeoServer, MapServer and share via GeoNetwork opensource metadata catalog. Your data is uploaded as a GeoPackage or shared PostGIS database.  GeoCat Bridge brings our celebrated symbology output to the QGIS Desktop to share your cartography online.

**Comment by volaya** [comment]
I changed the about ith you proposed text.

For lxml, the common way of adding dependencies is to ship them with the plugin.  It will be weird to have a python lib as a plugin, but even in that case it will only work for one OS. I dont think such a plugin will be aproved anyway
