### ISSUE TITLE
allow registering new live user from the plugin ui (no website)

### ISSUE THREAD

**Issue by volaya** [GeoCat/qgis-bridge-plugin#48]

**Comment by pvgenuchten** [comment]
"GeoCat Live" is the geocat cloud platform, by registering the instance on "GeoCat Live", users may receive a bonus experience on top of the default bridge experience. It's not clear what the bonus experience is, we're considering: 
- Easily order a (trial) cloud instance of Geoserver/Geonetwork
- Additional documentation
- Share user experiences with the developers

**Comment by volaya** [comment]
This can be closed
