### ISSUE TITLE
Trouble when Layer name and GeoPackage table name differ

### ISSUE THREAD

**Issue by jodygarnett** [GeoCat/qgis-bridge-plugin#53]
Layers are not correctly published when publishing for a geopackage and the layer name is not the same as the table name.

**Comment by jodygarnett** [comment]
Note the GeoServer REST API marks this difference as "nativeName", see https://docs.geoserver.org/latest/en/api/#/latest/en/api/1.0.0/featuretypes.yaml

**Comment by volaya** [comment]
this is fixed already
