### ISSUE TITLE
Import metadata from source

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#6]
A user should be enabled to import existing metadata for a dataset

- Metadata should be imported using various file conventions
  - [ ] Shapefile may include a .shp.xml file
  - [ ] Tiff has embedded metadata or it may include a .tiff.xml file
  - [ ] GeoPackage may have a [metadata table](http://www.geopackage.org/spec120/index.html#extension_metadata) with metadata records linked to data tables
  - [ ] WMS/ WFS/ WCS may have a link to a metadata record in a catalog
  - [ ] ESRI GDB has a metadata table
  - [ ] ESRI SDE stores a metadata record for each dataset in a metadata table
  (I'm currently not aware of any metadata conventions in Oracle/PostGIS)
  - [ ] alternatively a user could select a file on the filesystem to import
- metadata should be converted to the QMD format
  - [x] Suggest to start with an xslt from iso19139 & Dublin Core to QMD
  - Later consider to add support for iso19115-3, FGDC, DCAT, STAC ...

Idea is to have an 'import' button at the metadata screen (so making it import more explicit then auto importing it at file open event). 

This item has been discussed in the [qgis-metadata gitter](https://gitter.im/qgis/metadata?at=5d8b5395b6aa4d6c90dd5e32)

To consider is where to introduce this functionality, we probably need a separate module managing metadata conversions (we had some brainstorming around meta-dal, medal (gdal for metadata)). Current idea is to take a shortcut (single conversion), but allow it to be extended later to a meta-dal type of approach.

**Comment by pvgenuchten** [comment]
Alternative metadata models to consider form import/export are FGDC, iso19115-1, dcat

**Comment by timlinux** [comment]
Sometimes shapefiles also have metadata as ```filename.xml``` too.

**Comment by pvgenuchten** [comment]
For a first iteration, i'd suggest to start with shape, tiff & a user selecting a file manually

**Comment by volaya** [comment]
This is already implemented and the ticket can be closed
