### ISSUE TITLE
qgis can set a max width on a line style

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#67]
in qgis it is possible to set a line width in map units (getting wider when zooming in), but add a max width in mm, to not let it get too wide

![image](https://user-images.githubusercontent.com/299829/73615695-9c0df880-460a-11ea-8823-b1be78a471ba.png)

Bridge does not respect this and sets a width of 100px fixed.

Data used is available at https://github.com/tcoupin/qgis-server/tree/master/project, problematic layer is departments

**Comment by volaya** [comment]
How would you do that in SLD?
