### ISSUE TITLE
svg file not found

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#76]
when publishing a layer with a selected svg graphic, wms request resturns a svg file-not-found, are we uploading svg imagery to be used in symology?

![image](https://user-images.githubusercontent.com/299829/74044706-c6c1cd80-49cb-11ea-9bf1-651335c9433a.png)

**Comment by pvgenuchten** [comment]
in another project, when using an svg icon from qgis library, the icon seems to be uploaded fine, so maybe uploading failed, but the upload error was not reported?  if uploading fails, the style should not include a reference to that image and the layer should report a warning

**Comment by volaya** [comment]
The upload of the icon is not done separately. It goes in a zip file along with the xml.

In the qgis log you should see a message saying "style from layer XXX exported to [filename.zip]". Could you check that the zip file has the corresponding icon file?

**Comment by GeoSander** [comment]
Closing due to lack of response.
