### ISSUE TITLE
Test cycle summary [GeoCat Live]

### ISSUE THREAD

**Issue by volaya** [GeoCat/qgis-bridge-plugin#78]
The following is a set of elements to test before release:

Environment:

* GeoCat Live "standard"

  * GeoNetwork 3.4
  * GeoServer 2.13 - not sure what version
  * PostGIS - not sure

### Test data

There are two test QGIS projects in the `test` folder. The publishing operations must be tested with both of them, using a GeoCat Live instance for both GeoServer and GeoNetwork

### Publish tab
- [x] Check that project layers appear in the same order as in the QGIS TOC

- [x] Publish project to GeoServer and Geonetwork

- [x] Verify the following points:
	- Data is published correctly
	- Style is correctly published
	- Layer preview shows style as expected
	- Layer In GeoServer has correct pointer to GeoNetwork metadata url
	- Metadata in GeoNetwork correctly points at GeoServer data
- [x] Verify the following points (only for the test.qgs project):
	- Layers "original" and "sameorigin" use the same datastore (data is not uploaded twice and only one datastore is created)
        - Group is correctly created in GeoServer
        - Empty layer is not published and Bridge shows an error for that layer in the results dialog

- [x] Publish using "Publish in background" button

- [x] Publish project using "only symbology" option

- [x] Publish layer using only a reduced number of its fields

- [x] Test that metadata can be modified and edited from the metadata tab, and that it's saved to the layer metadata

- [x] Test that, if layers are published to data or metadata servers, the corresponding icons appear in the layers row.

- [x] Test elements in layer context menu, when data and metadata are published (open WMS, view metadata, etc)

- [x] Test "remove from server" button correctly removes data and metadata for all layers, and icons are correctly removed

 - [x] Test offline export

- [x] Test that, if trying to publish to GeoServer layers from a project that has not been saved, Bridge shows a warning message about it and does not allow publishing

### Servers tab

- [x] Test that servers can be added and removed

- [x] Test that, if a server has been modified and is not saved, Bridge shows a warning before moving to the "Publish tab", to a different server, or closing the dialog.

- [x] Test that Bridge complains when a new server is added and you try to save it with no auth configured

- [x] Test that, when server is wrong or cannot connect to it, a red frame is shown in the server selector, and the Publish buttons are disabled.

-  [x] Test opening and saving server configuration.
 	- Save your current configuration
 	- Delete servers manually in Bridge interface
 	- Load configuration from file

-  [x] Test that, when a GeoServer server is added, the corresponding WMS and WFS endpoints are added to QGIS

### GeoCat tab

- [ ] Test GeoCat welcome page is shown at first start when opening Bridge dialog
  (delete setting under geocatbridge/firstRun to force it, and then restart QGIS)

- [ ] Test that user can log to Live account and server urls are shown

- [ ] Test that, when the user logs to the Live account, a GeoCat Live server is added to the Servers tab automatically, only if a Live server for that user does not exist already

**Comment by pvgenuchten** [comment]
I tested some of the items above on a windows laptop having qgis 3.10 and on mac with qgis 3.10

**Comment by jodygarnett** [comment]
Thank you can you mark the things you tested please?

**Comment by volaya** [comment]
I tested with 3.12 and things publishing both data and metadata seems to be working fine. 

I founf an issue when trying to publish only metadata to Live, where Bridge complained about old geoserfver (even if not uploading data to it). I fixed it in this commit: https://github.com/GeoCat/qgis-bridge-plugin/commit/cbf49bf52751f0fd0d5b99f9d3951f3d0d9b7fe9

Other than that, looks like in 3.12 the plugin works like in 3.10

**Comment by jodygarnett** [comment]
excellent, can you mark the checkboxes above with what worked and what did not?

**Comment by GeoSander** [comment]
The GeoCat Live workflow has been moved to the private GeoCat repository. Testing will continue over there.
