### ISSUE TITLE
Test cycle Windows [local servers]

### ISSUE THREAD

**Issue by volaya** [GeoCat/qgis-bridge-plugin#79]
The following is a set of elements to test before release:

### Testing environment

* Desktop: Windows 10
  
  * QGIS 3.10
   
* Local Servers Windows
  
  * GeoNetwork 3.8 - run the installer
  * GeoServer Enterprise 2.16 - war available in Nexus, OpenJDK 8 (from adoptopenjdk) / Tomcat 9
  * PostGIS: Enterprise DB
   
### Test data

There are two test QGIS projects in the `test` folder. The publishing operations must be tested with both of them, using the above testing environment

### Publish tab

- [x] Publish project to GeoServer and Geonetwork

- [x] Verify the following points:
	- Data is published correctly
	- Style is correctly published
	- Layer preview shows style as expected
	- Layer In GeoServer has correct pointer to GeoNetwork metadata url
	- Metadata in GeoNetwork correctly points at GeoServer data
	- Layers "original" and "sameorigin" use the same datastore (data is not uploaded twice and only one datastore is created)

- [x] Publish using "Publish in background" button

- [x] Publish project using "only symbology" option

- [x] Publish layer using only a reduced number of its fields

- [x] Test that, if layers are published to data or metadata servers, the corresponding icons appear in the layers row.

- [x] Test elements in layer context menu, when data and metadata are published (open WMS, view metadata, etc)

- [x] Test "remove from server" button correctly removes data and metadata for all layers, and icons are correctly removed

**Comment by jodygarnett** [comment]
@pvgenuchten tested and opened https://github.com/GeoCat/qgis-bridge-plugin/issues/88

**Comment by jodygarnett** [comment]
Testing Feb 17 revision RC2:

- [ ] Publish project to GeoServer and Geonetwork

- [ ] Verify the following points:
	- Data is published correctly
	- Style is correctly published
	- Layer preview shows style as expected
	- Layer In GeoServer has correct pointer to GeoNetwork metadata url
	- Metadata in GeoNetwork correctly points at GeoServer data
	- Layers "original" and "sameorigin" use the same datastore (data is not uploaded twice and only one datastore is created)

- [ ] Publish using "Publish in background" button

- [ ] Publish project using "only symbology" option

- [ ] Publish layer using only a reduced number of its fields

- [ ] Test that, if layers are published to data or metadata servers, the corresponding icons appear in the layers row.

- [ ] Test elements in layer context menu, when data and metadata are published (open WMS, view metadata, etc)

- [ ] Test "remove from server" button correctly removes data and metadata for all layers, and icons are correctly removed

**Comment by jodygarnett** [comment]
@davidblasby testing Feb 16:

* osx qgis 3.10
* docker geoserver 2.16.2
* postgres 12 / postgis 3.0
* geonetwork live


- [ ] Publish project to GeoServer and Geonetwork

- [ ] Verify the following points:
	- Data is published correctly
	- Style is correctly published
	- Layer preview shows style as expected
	- Layer In GeoServer has correct pointer to GeoNetwork metadata url
	- Metadata in GeoNetwork correctly points at GeoServer data
	- Layers "original" and "sameorigin" use the same datastore (data is not uploaded twice and only one datastore is created)

- [ ] Publish using "Publish in background" button

- [ ] Publish project using "only symbology" option

- [ ] Publish layer using only a reduced number of its fields

- [ ] Test that, if layers are published to data or metadata servers, the corresponding icons appear in the layers row.

- [ ] Test elements in layer context menu, when data and metadata are published (open WMS, view metadata, etc)

- [ ] Test "remove from server" button correctly removes data and metadata for all layers, and icons are correctly removed

**Comment by jodygarnett** [comment]
@volaya can you update the checkboxs with what is tested for 4.0.x release please
