### ISSUE TITLE
AttributeError on publish layergroup

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#8]
When trying to publish a project with 2 layergroups (in workspace mode) i noticed this error.

```
plugins/geocatbridge/ui/publishwidget.py", line 540, in _layerGroups
              name = subchild.layer().name()
             AttributeError: 'QgsLayerTreeGroup' object has no attribute 'layer'
```

[groups.qgz.zip](https://github.com/GeoCat/qgis-bridge-plugin/files/3666457/groups.qgz.zip)

**Comment by volaya** [comment]
There was no support for nested groups. I added it ad this should be fixed already. Please, confirm, and close the ticket

**Comment by pvgenuchten** [comment]
@volaya please use the ['container tree' or 'named tree'](https://docs.geoserver.org/latest/en/user/data/webadmin/layergroups.html) mode for layergroups



in the current single mode, layers are not placed in a hierarchy in wms capabilities
