### ISSUE TITLE
qgis freezes when selecting: create "geocat live" connection, from drop down

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#83]
qgis freezes for multiple minutes when selecting the geocat live connection from the add server dropdown

![image](https://user-images.githubusercontent.com/299829/74442951-aa61dd00-4e72-11ea-9ca5-1b614697c565.png)

I force-quitted 3 times, but then decided to wait, it unfreezed after a couple of minutes

**Comment by volaya** [comment]
This was already fixed
