### ISSUE TITLE
challenges uploading mef metadata format

### ISSUE THREAD

**Issue by jodygarnett** [GeoCat/qgis-bridge-plugin#88]
Uploading mef fails using POST /api/records, identified gn behaves differently in 3.4 and 3.10
Uploading doesn't work via api-doc page

**Comment by jodygarnett** [comment]
We have two options for publishing:
- rest api
- csw transaction

**Comment by volaya** [comment]
does this recent change fix it?

https://github.com/GeoCat/qgis-bridge-plugin/commit/40669cc59a45cf11037a6c5bf6de3bda76655da2

**Comment by volaya** [comment]
This is already working fine. I am closing the ticket.
