### ISSUE TITLE
Workspace metadata

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#9]
When dynamically creating geoserver workspaces and mapserver mapfiles  use the project metadata to fill fields like title, abstract, contact for each workspace.

In Geoserver the workspace settings needs to be enabled:
![image](https://user-images.githubusercontent.com/299829/65828664-9c356a80-e29d-11e9-9c8a-681628207a37.png)
You can then set wms-settings for that workspace, having title/abstract:
![image](https://user-images.githubusercontent.com/299829/65828715-f6cec680-e29d-11e9-9410-83f9ee4ac198.png)

Project metadata in qgis is in project > properties

![image](https://user-images.githubusercontent.com/299829/65828734-3b5a6200-e29e-11e9-9acc-5e2131b29990.png)

**Comment by volaya** [comment]
What happens when i am publishing multiple layers into a workspace that I have to create?

**Comment by pvgenuchten** [comment]
Do you mean in 'free' mode when multiple layers are published into a single workspace? In that scenario I suggest not to fill the workspace metadata because it is not linked to 1 specific qgis project (users should complete the metadata themselves)

**Comment by volaya** [comment]
mm, that's is not only in 'free' mode. If you publish several layers, they all go to the same WS. It can be selected by the user in the geserver server configuration, or automatically selected using the project name, but in any case, there is a single WS for many layers. Should I do this only when you are uploading a single layer and the WS does not exist?

**Comment by pvgenuchten** [comment]
in non-workspace mode i could see a separate panel allowing to configure the workspace properties
another interesting panel at non-workspace mode is a listing of already published layers on that workspace, option to preview and manage them (similar to geoexplorer)

**Comment by pvgenuchten** [comment]
Qgis has a "qgis-server" tab in project properties, user is able to set a bunch of properties which are relevant as workspace properties in mapserver/geoserver

![image](https://user-images.githubusercontent.com/299829/68117013-851d1480-fefc-11e9-946d-afa24c56b877.png)

We could suggest users to fill this section and use it to configure the external server.
