### ISSUE TITLE
Import iso19139 to qml (via an xslt transform)

### ISSUE THREAD

**Issue by jodygarnett** [GeoCat/qgis-bridge-plugin#90]
@josegar74 are you able to provide to victor a basic iso19139 to qml transformation, we can later extend the conversion to capture more properties.

for use in a import option for metadata from shape/gpkg to qml

**Comment by jodygarnett** [comment]
This is an ongoing activity with the core qgis community to improve metadata support in QGIS Desktop.

Their suggestion is we first implement in Bridge and then donate to qgis core.

**Comment by volaya** [comment]
This is already implemented
