### ISSUE TITLE
convert esri-metadata to iso-metadata on import

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#96]
A nice new feature of bridge is to import existing metadata from the local source into the qgis project. As part of the import the metadata is converted from iso19139 to QML. However a lot of sources use a specific esri metadata format. Would be nice to be able to also import that metadata format. GeoNetwork provides a xslt which is able to convert the esri metadata to iso19139, which could be usefull.

https://github.com/geonetwork/core-geonetwork/blob/b28b332015d18e425c55a18ed6f8af99faf98f45/web/src/main/webapp/xsl/conversion/import/ArcCatalog8_to_ISO19115.xsl 

To verify is what is the license of this sheet.

**Comment by pvgenuchten** [comment]
From Bridge 3 code

```
	
12:18 PM



If Metadata format = FGDC
   Apply ArcCatalogEsriIso_to_ISO19115.xsl
   Apply to previous result 19115_to_19139.xsl
Else If Metadata format = ESRI ISO (ISO19115) 
   Apply 19115_to_19139.xsl
Else If Metadata format = ISO19139
  No transformation to apply
```

Also consider the case called "geosticker", in this case a full iso19139 document is embedded in a <esri> header, check for <md_metadata> within <esri>, if exists; remove the esri header from the document.

**Comment by pvgenuchten** [comment]
zip with example of esri md and geosticker md
[mds.zip](https://github.com/GeoCat/qgis-bridge-plugin/files/4337975/mds.zip)

**Comment by volaya** [comment]
This is implemented already
