### ISSUE TITLE
Severe publishing problems

### ISSUE THREAD

**Issue by matself** [GeoCat/qgis-bridge-plugin#97]
This may be a user error, but I have failed troubleshooting. Or is it a bug? I will try to give a complete bug report.
### Local QGIS setup
Windows 10 Pro, QGIS 3.10.2, Geocat bridge plugin 4.0.1
### Remote server setup
Windows 2012 R2 Datacenter, PostgreSQL 11.6, PostGIS 3.0.0
Apache Tomcat/9.0.30, JVM 1.8.0_242-b08 (AdoptOpenJDK)
GeoServer 2.16.2, GeoNetwork 3.10.0.0 (both under Tomcat from war files)
### Plugin setup
The Plugin was installed by copying the unzipped plugin folder to my current plugin folder. Connections are setup to a dedicated PostGIS db for GeoCat Bridge, and the above defined GeoServer and GeoNetwork instances. All connections are validated to work with the GeoCat Connect button. QGIS also can connect to PostGIS and GeoServer.
### Failed attempt to Publish
Using open data, I try to publish three layers, one point, one line and one polygon layer. Symbology is very simple, using QGIS standard symbology. I have tried various settings and groupings, but the publishing invariably fails. Here is the Geoserver log from a failed attempt.
```
2020-02-18 22:55:20,674 INFO [rest.catalog] - DELETE workspace WorkspaceInfoImpl[geocatbridge]
2020-02-18 22:55:20,799 INFO [rest.catalog] - Added workspace geocatbridge
2020-02-18 22:55:20,799 INFO [rest.catalog] - POST workspace geocatbridge
2020-02-18 22:55:21,016 INFO [rest.catalog] - POST Style Package: mb_12, workspace: geocatbridge
2020-02-18 22:55:21,234 INFO [rest.catalog] - PUT Style Package: mb_12, workspace: geocatbridge
2020-02-18 22:57:00,722 INFO [rest.catalog] - POST Style Package: kl_12, workspace: geocatbridge
2020-02-18 22:57:00,985 INFO [rest.catalog] - PUT Style Package: kl_12, workspace: geocatbridge
2020-02-18 22:57:13,991 INFO [rest.catalog] - POST Style Package: ns_12, workspace: geocatbridge
2020-02-18 22:57:14,203 INFO [rest.catalog] - PUT Style Package: ns_12, workspace: geocatbridge
```
As you can see, a workspace is created and styles are uploaded.
**No Stores are created
No Layers are created**
Here is the error message from the Bridge plugin.
`Traceback (most recent call last): File "C:/Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\publishtask.py", line 132, in run self.geodataServer.publishLayer(layer, fields) File "C:/Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\geoserver.py", line 109, in publishLayer self._publishVectorLayerFromPostgis(layer) File "C:/Users/GisKraft/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\geoserver.py", line 186, in _publishVectorLayerFromPostgis db = allServers()[self.postgisdb] NameError: name 'allServers' is not defined`
### Geonetwork publishing
However, and very irrational, valid Geonetwork posts are written for all attempted layers, with a wms link that would have been correct if a wms layer had been created. The metadata post also contains a correct thumbnail, using the right symbology, and a correct layer bounds.
### PostGIS data upload
Data upload works as well. PostGIS tables are created and populated (drop and create probably) with the correct data.
### Conclusion
GeoCat bridge fails for all practical purposes. Parts are working, but the most important bit is missing. Also, the plugin deletes manually published layers in the Workspace because it deletes the entire workspace. Styles are overwritten as well, which invalidates manually published layers in other workspaces using the same styles. This behavior can cause severe data loss if not clearly documented.

**Comment by volaya** [comment]
@matself thanks for your comments.

The error you are seeing happens when trying to create the geoserver datastore that points to your postgis table (which is created correctly, as you mention). That issue was fixed very recently in this commit: https://github.com/GeoCat/qgis-bridge-plugin/commit/2e31e46f56021844ab3d650529439824114c82e8

Please, checkout the latest version and try again.

About the workspace being deleted, that's intentional. It is documented in the Bridge documentation. See here: https://www.geocat.net/docs/bridge/qgis/v4.0/server_configuration.html#bridge-and-geoserver-workspaces

Thanks again for your detailed report. If you find any other issue, please let us know.

**Comment by pvgenuchten** [comment]
Bridge 3 has a warning if layers are detected in the remote workspace that are not in the current project, to indicate these layers would be removed by the current publication. With the option to cancel the publication process. I guess we need similar here to prevent the experience described here.

**Comment by cvanlith** [comment]
I was not aware that the qgis project name is used as the workspace name when publising to geoserver (using bridge for qgis 4.0.2). Yes I know RTFM. By coincidence I named the qgis project exactly the same as the workspace I was using for several datasets.
Pressing the publish button removed all the layers without any warning :-(
Please add some warning.

**Comment by volaya** [comment]
Warning added. If the WS already exist and has layers that are not going to be republished (so they will be deleted), a confirmation dialog is shown
