### ISSUE TITLE
Error while unloading plugin Geocatbridge

### ISSUE THREAD

**Issue by rjhale1971** [GeoCat/qgis-bridge-plugin#98]
I'm running QGIS 3.11 Master Revision ced0ed4c79
If I load the plugin and close QGIS everything is fine. If I have data loaded and close QGIS I get an error: 

Error while unloading plugin geocatbridge
-------------------------------------------------------

Error while unloading plugin geocatbridge 

RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 434, in unloadPlugin
    plugins[packageName].unload()
  File "/home/rjhale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/plugin.py", line 105, in unload
    layer.styleChanged.disconnect(func)
RuntimeError: wrapped C/C++ object of type QgsVectorLayer has been deleted

Python version: 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008] 
QGIS version: 3.11.0-Master Master, ced0ed4c79 

Python Path:
/usr/share/qgis/python
/home/rjhale/.local/share/QGIS/QGIS3/profiles/default/python
/home/rjhale/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/dist-packages
/usr/lib/python3/dist-packages
/home/rjhale/.local/share/QGIS/QGIS3/profiles/default/python
/home/rjhale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs
/home/rjhale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle

**Comment by jodygarnett** [comment]
Thanks @rjhale1971, we tend to focus on the stable release. Can I ask why you are running 3.11?

I would like to invite you to start a trial when we announce this week, we can then treat this as a support issue.

**Comment by rjhale1971** [comment]
Once month before final release I install the current master and start bug reporting - I had installed Geocat and noticed it was crashing QGIS on close. I checked just now and it's fine with 3.12. So yay.

**Comment by volaya** [comment]
Hi @rjhale1971, thanks for the report. The error is not linked to QGIS version, but instead to an existing bug that caused an excepcion when a layer had been added and then removed from the QGIS project before unloading the plugin. This commit should fix it:

https://github.com/GeoCat/qgis-bridge-plugin/commit/8c01cc5aef3bf1f1f9340eb6af665ba803635cc9

Thanks again!

**Comment by rjhale1971** [comment]
Holy Crap - It's Victor. I'm not worthy!
